# Generated by Django 4.1.1 on 2022-09-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='content_type',
            field=models.TextField(default='image/bmp', max_length=500),
            preserve_default=False,
        ),
    ]
